// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-kT7OuiuLEoTFyFcgsYEBE_N1faOpqj8',
    appId: '1:616040824437:web:ccc06e3b8d9ad91354823c',
    messagingSenderId: '616040824437',
    projectId: 'ecotrack-c8a41',
    authDomain: 'ecotrack-c8a41.firebaseapp.com',
    storageBucket: 'ecotrack-c8a41.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMB2sZyQG7i7hO0yZd_DoYH3Lv_s7Wlfo',
    appId: '1:616040824437:android:7f11ff32b66a062c54823c',
    messagingSenderId: '616040824437',
    projectId: 'ecotrack-c8a41',
    storageBucket: 'ecotrack-c8a41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZdtXVoGkUclzzcIUrZha8hhJYJ1XHCdw',
    appId: '1:616040824437:ios:e4c0d4df43bc619d54823c',
    messagingSenderId: '616040824437',
    projectId: 'ecotrack-c8a41',
    storageBucket: 'ecotrack-c8a41.appspot.com',
    iosBundleId: 'com.example.providerStateManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZdtXVoGkUclzzcIUrZha8hhJYJ1XHCdw',
    appId: '1:616040824437:ios:e4c0d4df43bc619d54823c',
    messagingSenderId: '616040824437',
    projectId: 'ecotrack-c8a41',
    storageBucket: 'ecotrack-c8a41.appspot.com',
    iosBundleId: 'com.example.providerStateManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-kT7OuiuLEoTFyFcgsYEBE_N1faOpqj8',
    appId: '1:616040824437:web:189fb5ff99ce614e54823c',
    messagingSenderId: '616040824437',
    projectId: 'ecotrack-c8a41',
    authDomain: 'ecotrack-c8a41.firebaseapp.com',
    storageBucket: 'ecotrack-c8a41.appspot.com',
  );
}
